### ISSUE TITLE
Number of pages transcribed

### ISSUE THREAD

**Issue by Ebtessam** [Daniel-KM/Scripto#4]
is it possible to get the number of pages transcribed till now?

**Comment by Daniel-KM** [comment]
Hi,

Yes.
By default, these informations are saved in the elements "Status", "Percent Needs Review" and "Percent Completed", that you can get via the standard metadata() function.

If you want the precise number, you need to get it:
```php
$doc = $scripto->getDocument($item->id);
$counts = $doc->getItemStatusCounts();
```

"$counts" is an associative array: 
```php
array(
    'total' => $totalPages,
    'completed' => $completed,
    'partial' => $partial,
    'notStarted' => $notStarted,
);
```


Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Ebtessam** [comment]
but this applies to pages of an item am I correct? nothing for the total pages transcribed till now in all collections?

Cheers,
Ebtessam Zoheir

**Comment by Daniel-KM** [comment]
Hi,

Yes. To get the full number, extract it directly via a sql query, or make a loop.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Ebtessam** [comment]
Ok thanks alot, great library.
