### ISSUE TITLE
Item and Collections 

### ISSUE THREAD

**Issue by basepoder** [Daniel-KM/Scripto#5]
Hi Daniel
Thanks for your help on getting scribe on and running. It's working like a charm :)

But two things keeps me awake at night - almost

When you click on Items and collection nothing really happens. And on the frontpage the items seems to loop. Once again it's properly the a F40 error :) 
http://pedersorensen.basecrowd.dk/

**Comment by Daniel-KM** [comment]
Hi,

In this theme, items/browse is redirected to collections/browse. Default links are still displayed, so this explains your issue. You can remove links in the theme or you can enable the default items/browse page (delete items/browse.php in the Scribe theme). 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by basepoder** [comment]
Perfect!!!
Once again: thanks a lot! 😃


Best!

Den mandag den 4. juli 2016 skrev Daniel Berthereau <
notifications@github.com>:

> Hi,
>
> In this theme, items/browse is redirected to collections/browse. Default
> links are still displayed, so this explains your issue. You can remove
> links in the theme or you can enable the default items/browse page (delete
> items/browse.php in the Scribe theme).
>
> Sincerely,
>
> Daniel Berthereau
> Infodoc & Knowledge management
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Daniel-KM/Scripto/issues/5#issuecomment-230204908>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATU3OhsMTgulvU9BA_GlNxw0ZQchsGaRks5qSJJXgaJpZM4JD3pG>
> .
>


-- 
Med venlig hilsen


Søren K. Poder


Helenelyst 166
DK - Brabrand N
Tlf.: 21 83 57 12
soren@kpoder.dk
www.sorenkpoder.dk
