### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by papermartine** [Daniel-KM/Scripto#6]
Hi Daniel, 

I can't seem to get the 'Create an Account' link to work. It continues to redirect back to the 'Login' page. Any suggestions? I see that 'register.php' code was added last year so I re-installed Scripto. Thank you for the  help!

-km

**Comment by Daniel-KM** [comment]
Hi,

I just fixed this issue and added a link to "Register".

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
